### ISSUE TITLE
Publish fails

### ISSUE THREAD

**Issue by hsytkm** [nuitsjp/Wpf.Extensions.Hosting#3]
## Introduction

This problem may not be caused by this library. Please let me know what you know.

## Describe the bug

Build succeeds, but publish fails.

## Steps to reproduce

1. Create a new WPF project in .NET 7.
2. Follow the [Getting Started](https://github.com/nuitsjp/Wpf.Extensions.Hosting#getting-started) instructions.
3. Build -> Succeed
4. Publish -> Failed

Below is the reproduced repository.

https://github.com/hsytkm/WpfExtensionsHostingDemo

## Expected behavior

Build and publish results should match.

## Actual behavior

Only the publish fails.  This is the same result for both Framework-dependent and Self-contained.

## Environment

- Wpf.Extensions.Hosting: 1.1.2
- OS: Windows 11 22H2 22621.1635
- Target Framework: .NET 7
- Visual Studio 1: 2022 17.5.5
- Visual Studio 2: 2022 17.6.0 Preview 6.0

## Screenshots
![publish_error](https://user-images.githubusercontent.com/34601860/236682226-18dc3ae8-0996-4480-bc9a-e2d75c38f51e.gif)

**Comment by nuitsjp** [comment]
Thanks for contacting me! 
I will look into it. Please wait a moment.

**Comment by nuitsjp** [comment]
I tried a few.

- Run from Visual Studio's publish command.
    - x86 : Error
    - x64 : Error
- Execute "dotnet publish" from the console
    - x86 : Success
    - x64 : Success

There may be some mistake related to "global using", but it may not be solved immediately. 
Is there a workaround with the dotnet command if it is urgently needed?

**Comment by hsytkm** [comment]
Thank you for your reply.

I can avoid this problem by adding redundant usings to Program.c, as per the uploaded gif animation.
So it's not urgent.

### Test results

It looks like you weren't able to reproduce it in your environment.

Here are some additional results I have tried.

#### Visual Studio publish menu

All of the following **failed**.

- Self-contained + win-x86
- Framework-dependent + win-x86
- Self-contained + win-x64
- Framework-dependent + win-x64

#### donet command from console

All of the below **succeeded** .

```powershell
dotnet publish -c Release -p:PublishSingleFile=true --self-contained -r win-x86
dotnet publish -c Release -p:PublishSingleFile=true --no-self-contained -r win-x86
dotnet publish -c Release -p:PublishSingleFile=true --self-contained -r win-x64
dotnet publish -c Release -p:PublishSingleFile=true --no-self-contained -r win-x64
```

**Comment by nuitsjp** [comment]
Sorry. The earlier statement is wrong and I am reproducing it in my environment.
From VS, it succeeds only when TargetRuntime is portable.

The reason is still that the global using added by Implicit Using is not working properly.
I don't know how to implement it correctly right now, so I'll do some research.

Since you say you are not in a hurry, please wait a bit.

**Comment by nuitsjp** [comment]
I am looking into this but am struggling a lot.
It may not be possible from the class library side.

If I specify "win-x64" in RuntimeIdentify in csproj on the user side, it works.
However, if you specify more than one RuntimeIdentifiys, it will not work "for the first time".
If I issue each RuntimeIdentify and then specify RuntimeIdentifiys, it works.

However, with a simple project, it does not reproduce.
Please give me some more time as I am having a hard time isolating the cause.

**Comment by nuitsjp** [comment]
I have done some research, but when I use the Publish function from the Visual Studio GUI, the publish fails under at least the following conditions.

1. a WPF project
2. contains MainWindow.xaml (App.xaml is fine)
3. it references a NuGet package that automatically adds "global using
4. using class 3 without explicitly specifying "using".
5. not specifying RuntimeIdentifier in WPF project.
6. you issue the target runtime specifying something other than "portable"

If any one of the above conditions is different, the issue will succeed.

If you specify RuntimeIdentifiers instead of RuntimeIdentifier, it will fail.

There seems to be no way to deal with this from the library side, so I will report this once to Microsoft.

Sorry, but until this is resolved on the VS side, please use one of the following workarounds. 1.

1. use the dotnet publish command
2. Specify RuntimeIdentifier
3. add explicitly using

**Comment by hsytkm** [comment]
I appreciate your detailed investigation.

I understood that it's difficult to fix the problem by modifying with a library side.

I'll use these workarounds you have suggested.

**Comment by nuitsjp** [comment]
I have provided feedback to the Visual Studio development side.
If you would like to "Votes" for it, that would be great.

https://developercommunity.visualstudio.com/t/When-publishing-from-Visual-Studio-G/10362167

**Comment by nuitsjp** [comment]
In the end, there was no problem with Wpf.Extensions.Hosting.
Therefore, the Issue is closed once.
Thank you for your kind report and the reproduced code. It was very helpful!
If there is any response to the VS submission, I would like to provide feedback here as well.
